language: ruby
rvm:
  - 2.3.3

sudo: false
branches:
  only:
    - src

install:
  - gem install jekyll
  - curl https://sh.rustup.rs > temp.sh
  - chmod +x temp.sh
  - ./temp.sh -y
  - source $HOME/.cargo/env
  - rm temp.sh
  - cargo install mdbook
  - gem install jekyll-paginate

script: ./buildToMaster
env:
  global:
    - ENCRYPTION_LABEL: "f45b69d04d69"
    - COMMIT_AUTHOR_EMAIL: "donald_pinckney@icloud.com"

notifications:
  email: false