language: ruby
rvm:
  - 2.3.3

sudo: false
dist: trusty
branches:
  only:
    - src

install:
  - curl https://sh.rustup.rs -sSf | sh
  - cargo install mdbood

script: ./buildToMaster
env:
  global:
    - ENCRYPTION_LABEL: "f45b69d04d69"
    - COMMIT_AUTHOR_EMAIL: "donald_pinckney@icloud.com"

notifications:
  email: false