language: ruby
rvm:
  - 2.3.3

sudo: false
branches:
  only:
    - src   

script: ./buildToMaster
env:
  global:
    - ENCRYPTION_LABEL: "f45b69d04d69"
    - COMMIT_AUTHOR_EMAIL: "donald_pinckney@icloud.com"